# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[collab-vm-web-app] - Node.js Gulp"

on:
  push:
    branches: [ master, semantic ]
  pull_request:
    branches: [ master ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.result }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip];[no ci]'
          commit-filter-separator: ';'
      - run: echo "::set-output name=result::${CI_SKIP}"
        id: result_step

  gulp:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global gulp-cli
    - run: npm install
    - run: gulp
    - name: Upload Artifacts
      uses: 'actions/upload-artifact@v2'
      with:
        name: Web App built by Node ${{ matrix.node-version }}
        path: './build/*'
